/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksystem;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

public class CreateAcc extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogIn
     */
    public CreateAcc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contactNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emergencyNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AccId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Agreement = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        AccCreateButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        BackMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(104, 0, 38));
        jPanel1.setPreferredSize(new java.awt.Dimension(1390, 732));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 0, 38));
        jLabel1.setText("First Name :");

        FirstName.setForeground(new java.awt.Color(104, 0, 38));

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 0, 38));
        jLabel2.setText("Last Name :");

        LastName.setForeground(new java.awt.Color(104, 0, 38));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(104, 0, 38));
        jLabel3.setText("Birth Date :");

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(104, 0, 38));
        jLabel4.setText("Email :");

        DOB.setForeground(new java.awt.Color(104, 0, 38));
        DOB.setText("YYYY-MM-DD");
        DOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBFocusLost(evt);
            }
        });
        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });

        email.setForeground(new java.awt.Color(104, 0, 38));
        email.setText("username@gmail.com");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        contactNum.setForeground(new java.awt.Color(104, 0, 38));
        contactNum.setText("03XX-XXXXXXX");
        contactNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactNumFocusLost(evt);
            }
        });
        contactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 0, 38));
        jLabel5.setText("Contact no:");

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(104, 0, 38));
        jLabel6.setText("Emergency Contact :");

        emergencyNum.setForeground(new java.awt.Color(104, 0, 38));
        emergencyNum.setText("03XX-XXXXXXX");
        emergencyNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergencyNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emergencyNumFocusLost(evt);
            }
        });
        emergencyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyNumActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(104, 0, 38));
        jLabel7.setText("CNIC Number :   ");

        cnic.setForeground(new java.awt.Color(104, 0, 38));
        cnic.setText("XXXXX-XXXXXX-X");
        cnic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicFocusLost(evt);
            }
        });
        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(104, 0, 38));
        jLabel8.setText("City :");

        City.setForeground(new java.awt.Color(104, 0, 38));
        City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CityFocusLost(evt);
            }
        });
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(104, 0, 38));
        jLabel9.setText("Address :");

        address.setForeground(new java.awt.Color(104, 0, 38));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(104, 0, 38));
        jLabel10.setText("Set Account ID");

        AccId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AccIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AccIdFocusLost(evt);
            }
        });
        AccId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccIdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(104, 0, 38));
        jLabel12.setText("-Must have three Capital characters.");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(104, 0, 38));
        jLabel13.setText("-Numbers between 3-12");

        jLabel14.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(104, 0, 38));
        jLabel14.setText("Set Password");

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(104, 0, 38));
        jLabel16.setText("-Must be atleast 8 characters long");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(104, 0, 38));
        jLabel17.setText("-Must contain one uppercase letter");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(104, 0, 38));
        jLabel18.setText("-Must contain one lowercase letter");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(104, 0, 38));
        jLabel19.setText("-Must contain one special character");

        Agreement.setForeground(new java.awt.Color(104, 0, 38));
        Agreement.setText("Agreeing to terms & conditions");
        Agreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreementActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Bradley Hand ITC", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(104, 0, 38));
        jLabel21.setText("Create Account Form");

        AccCreateButton.setBackground(new java.awt.Color(104, 0, 38));
        AccCreateButton.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        AccCreateButton.setForeground(java.awt.Color.white);
        AccCreateButton.setText("Create Account");
        AccCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(89, 89, 117), new java.awt.Color(204, 204, 255)));
        AccCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccCreateButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(104, 0, 38));
        jLabel20.setText("Balance :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agreement))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(password)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel20))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(AccId))
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emergencyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(AccCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(214, 214, 214))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel11)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emergencyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(14, 14, 14)))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agreement)
                .addGap(18, 18, 18)
                .addComponent(AccCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        BackMain.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        BackMain.setForeground(new java.awt.Color(104, 0, 38));
        BackMain.setText("Back to main");
        BackMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(89, 89, 117), new java.awt.Color(204, 204, 255)));
        BackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackMain)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusGained
        if (DOB.getText().equals("YYYY-MM-DD")) {
            DOB.setText("");
        }
    }//GEN-LAST:event_DOBFocusGained

    private void DOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusLost

        if (!dateValidator(DOB.getText())) {
            if (DOB.getText().equals("")) {
                DOB.setText("YYYY-MM-DD");
            } else {
                JOptionPane.showMessageDialog(this, "Please enter valid date!");
            }

        }

    }//GEN-LAST:event_DOBFocusLost

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed

    }//GEN-LAST:event_DOBActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if (email.getText().equals("username@gmail.com")) {
            email.setText("");// TODO add your handling code here:
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if (!emailValidator(email.getText())) {
            if (email.getText().equals("")) {
                email.setText("username@gmail.com");// TODO add your handling code here:
            } else {
                JOptionPane.showMessageDialog(this, "Please enter valid email!");
            }
        }

    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void contactNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactNumFocusGained
        if (contactNum.getText().equals("03XX-XXXXXXX")) {
            contactNum.setText("");
        }

    }//GEN-LAST:event_contactNumFocusGained

    private void contactNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactNumFocusLost

        if (!numberValidator(contactNum.getText())) {
            if (contactNum.getText().equals("")) {
                contactNum.setText("03XX-XXXXXXX");
            } else {
                JOptionPane.showMessageDialog(this, "Please enter valid contact number of format 03XX-XXXXXXX!");
            }
        }
    }//GEN-LAST:event_contactNumFocusLost

    private void contactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumActionPerformed

    }//GEN-LAST:event_contactNumActionPerformed

    private void emergencyNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyNumFocusGained
        if (emergencyNum.getText().equals("03XX-XXXXXXX")) {
            emergencyNum.setText("");
        }
    }//GEN-LAST:event_emergencyNumFocusGained

    private void emergencyNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyNumFocusLost

        if (!numberValidator(emergencyNum.getText())) {
            if (emergencyNum.getText().equals("")) {
                emergencyNum.setText("03XX-XXXXXXX");
            } else {
                JOptionPane.showMessageDialog(this, "Please enter valid contact number of format 03XX-XXXXXXX!");
            }
        }
    }//GEN-LAST:event_emergencyNumFocusLost

    private void emergencyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyNumActionPerformed

    }//GEN-LAST:event_emergencyNumActionPerformed

    private void cnicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFocusGained
        if (cnic.getText().equals("XXXXX-XXXXXX-X")) {
            cnic.setText("");
        }
    }//GEN-LAST:event_cnicFocusGained

    private void cnicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFocusLost

        if (!cnicValidator(cnic.getText())) {
            if (cnic.getText().equals("")) {
                cnic.setText("XXXXX-XXXXXX-X");
            } else {

                JOptionPane.showMessageDialog(this, "Please enter valid CNIC!");
            }
        }
    }//GEN-LAST:event_cnicFocusLost

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed

    }//GEN-LAST:event_cnicActionPerformed

    private void CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CityFocusGained

    private void CityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_CityFocusLost

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFocusLost

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void AccIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AccIdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_AccIdFocusGained

    private void AccIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AccIdFocusLost
        if (!bankAccountNumberValidator(AccId.getText()))
            if (!AccId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter valid Account number!");
            }
    }//GEN-LAST:event_AccIdFocusLost

    private void AccIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccIdActionPerformed

    }//GEN-LAST:event_AccIdActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (!passwordValidator(password.getText())) {
            if (!password.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter valid password!");
            }
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        Pattern pattern = Pattern.compile(passwordRegex);
        Matcher matcher = pattern.matcher(password.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Please enter valid password.");
        }

    }//GEN-LAST:event_passwordActionPerformed

    private void AgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgreementActionPerformed

    private void AccCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccCreateButtonActionPerformed
        String URL = "jdbc:mysql://localhost:3306/BankSystem";
        String Username = "root";
        String Password = "Radhika1@";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try (Connection connect = DriverManager.getConnection(URL, Username, Password)) {
            // Check for empty fields and valid input
            if (!(Agreement.isSelected()) || AccId.getText().equals("") || password.getText().equals("")
                    || FirstName.getText().equals("") || LastName.getText().equals("")
                    || DOB.getText().equals("YYYY-MM-DD") || email.getText().equals("username@gmail.com")
                    || contactNum.getText().equals("03XX-XXXXXXX") || emergencyNum.getText().equals("03XX-XXXXXXX")
                    || cnic.getText().equals("XXXXX-XXXXXX-X") || City.getText().equals("") || address.getText().equals("") || balance.getText().equals("")) {

                if (!(Agreement.isSelected())) {
                    JOptionPane.showMessageDialog(this, "The terms and conditions have not been agreed upon.");
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter data into remaining field(s)");
                }
            } else if (!passwordValidator(password.getText()) || !bankAccountNumberValidator(AccId.getText())
                    || !dateValidator(DOB.getText()) || !emailValidator(email.getText())
                    || !numberValidator(contactNum.getText()) || !numberValidator(emergencyNum.getText())
                    || !cnicValidator(cnic.getText())) {

                JOptionPane.showMessageDialog(this, "Please enter valid values!");
                if (!passwordValidator(password.getText())) {
                    password.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!bankAccountNumberValidator(AccId.getText())) {
                    AccId.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!dateValidator(DOB.getText())) {
                    DOB.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!emailValidator(email.getText())) {
                    email.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!numberValidator(contactNum.getText())) {
                    contactNum.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!numberValidator(emergencyNum.getText())) {
                    emergencyNum.setBorder(BorderFactory.createLineBorder(Color.RED));
                }
                if (!cnicValidator(cnic.getText())) {
                    cnic.setBorder(BorderFactory.createLineBorder(Color.RED));
                }

            } else {
                // Check if accountID already exists
                String checkQuery = "SELECT COUNT(*) FROM accounts WHERE accountID = ?";
                try (PreparedStatement checkStmt = connect.prepareStatement(checkQuery)) {
                    checkStmt.setString(1, AccId.getText());
                    ResultSet rs = checkStmt.executeQuery();
                    rs.next();
                    int count = rs.getInt(1);

                    if (count > 0) {
                        JOptionPane.showMessageDialog(this, "Account ID already exists. Please choose a different ID.");
                    } else {
                        // Proceed with insertion
                        String query = "INSERT INTO accounts (FirstName, LastName, DOB, Email, PhoneNumber, EmergencyNum, CNIC, City, Address, accountID, Password, balance) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        try (PreparedStatement statement = connect.prepareStatement(query)) {
                            statement.setString(1, FirstName.getText());
                            statement.setString(2, LastName.getText());
                            statement.setDate(3, StringToDate(DOB.getText()));
                            statement.setString(4, email.getText());
                            statement.setString(5, contactNum.getText());
                            statement.setString(6, emergencyNum.getText());
                            statement.setString(7, cnic.getText());
                            statement.setString(8, City.getText());
                            statement.setString(9, address.getText());
                            statement.setString(10, AccId.getText());
                            statement.setString(11, password.getText());
                            statement.setDouble(12, Double.parseDouble(balance.getText()));
                            int insertRow = statement.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Account has been created.");

                            dispose();
                            MainMenu main = new MainMenu();
                            main.pack();
                            main.setLocationRelativeTo(null);
                            main.show();
                        } catch (ParseException ex) {
                            Logger.getLogger(CreateAcc.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_AccCreateButtonActionPerformed
    private Date StringToDate(String dateStr) throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = formatter.parse(dateStr);
        return new Date(date.getTime());
    }
    private void BackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMainActionPerformed
        dispose();
        MainMenu main = new MainMenu();
        main.pack();
        main.setLocationRelativeTo(null);
        main.show();

    }//GEN-LAST:event_BackMainActionPerformed

    private boolean passwordValidator(String pass) {
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        Pattern pattern = Pattern.compile(passwordRegex);
        Matcher matcher = pattern.matcher(pass);
        return matcher.matches();
    }

    private boolean bankAccountNumberValidator(String accountNumber) {
        // Regular expression for bank account numbers (8 to 12 digits)
        String accountNumberRegex = "^[A-Z]{3}[0-9]{3,8}$"; // 3 capital letters followed by 3 to 8 digits
        Pattern pattern = Pattern.compile(accountNumberRegex);
        Matcher matcher = pattern.matcher(accountNumber);
        return matcher.matches();
    }

    private boolean dateValidator(String pass) {
        String regex = "^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(DOB.getText());
        return matcher.matches();
    }

    private boolean emailValidator(String pass) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@gmail.com";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email.getText());
        return matcher.matches();
    }

    private boolean numberValidator(String pass) {
        String regex = "^03\\d{2}-?\\d{7}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(contactNum.getText());
        return matcher.matches();
    }

    private boolean cnicValidator(String pass) {
        String regex = "^\\d{5}-?\\d{6}-?\\d{1}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(cnic.getText());
        return matcher.matches();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccCreateButton;
    private javax.swing.JTextField AccId;
    private javax.swing.JCheckBox Agreement;
    private javax.swing.JButton BackMain;
    private javax.swing.JTextField City;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField address;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField contactNum;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emergencyNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables

}
