/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksystem;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public Transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        Transfer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        accNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(104, 0, 38));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSACTION");

        Username.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Name:");

        User.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        User.setForeground(java.awt.Color.white);
        User.setText("User");

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Account no. :");

        ID.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        ID.setForeground(java.awt.Color.white);
        ID.setText("jLabel3");

        Back.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(104, 0, 38));
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addComponent(User))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username)
                            .addComponent(User))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(104, 0, 38));
        jLabel3.setText("AMOUNT :");

        amount.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        Transfer.setBackground(new java.awt.Color(104, 0, 38));
        Transfer.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Transfer.setForeground(java.awt.Color.white);
        Transfer.setText("Transfer");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(104, 0, 38));
        jLabel4.setText("ACCOUNT NO:");

        accNo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        accNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Transfer)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        String URL = "jdbc:mysql://localhost:3306/BankSystem";
        String username = "root";
        String password = "Radhika1@";

        double bal = 0.0;
        String senderID = ID.getText();  // Sender's account ID
        String receiverID = accNo.getText();  // Receiver's account ID
        String amountText = amount.getText();

        if (amountText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the amount first!");
            return;
        }
        if (receiverID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the receiver's account number!");
            return;
        }

        double transferAmount;
        try {
            transferAmount = Double.parseDouble(amountText);
            if (transferAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid amount!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format!");
            return;
        }

        if (senderID.equals(receiverID)) {
            JOptionPane.showMessageDialog(this, "You cannot transfer money to your own account!");
            return;
        }

        Connection conn = null;
        PreparedStatement stmt = null;
        PreparedStatement withdrawStmt = null;
        PreparedStatement depositStmt = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(URL, username, password);
            conn.setAutoCommit(false); // Start transaction

            // Verify sender's account existence and check balance
            String selectSenderQuery = "SELECT balance FROM Accounts WHERE accountID = ?";
            stmt = conn.prepareStatement(selectSenderQuery);
            stmt.setString(1, senderID);
            ResultSet senderRS = stmt.executeQuery();

            if (senderRS.next()) {
                bal = senderRS.getDouble("balance");
            } else {
                JOptionPane.showMessageDialog(this, "Sender's account not found!");
                conn.rollback(); // Rollback transaction on error
                return;
            }

            // Verify receiver's account existence
            String selectReceiverQuery = "SELECT 1 FROM Accounts WHERE accountID = ?";
            PreparedStatement receiverStmt = conn.prepareStatement(selectReceiverQuery);
            receiverStmt.setString(1, receiverID);
            ResultSet receiverRS = receiverStmt.executeQuery();

            if (!receiverRS.next()) {
                JOptionPane.showMessageDialog(this, "Receiver's account not found!");
                conn.rollback(); // Rollback transaction on error
                return;
            }

            if (bal < transferAmount) {
                JOptionPane.showMessageDialog(this, "Insufficient funds in your account!");
                conn.rollback(); // Rollback transaction on error
                return;
            }

            // Withdraw money from sender's account
            String withdrawSQL = "UPDATE Accounts SET balance = balance - ? WHERE accountID = ?";
            withdrawStmt = conn.prepareStatement(withdrawSQL);
            withdrawStmt.setDouble(1, transferAmount);
            withdrawStmt.setString(2, senderID);
            withdrawStmt.executeUpdate();

            // Deposit money into receiver's account
            String depositSQL = "UPDATE Accounts SET balance = balance + ? WHERE accountID = ?";
            depositStmt = conn.prepareStatement(depositSQL);
            depositStmt.setDouble(1, transferAmount);
            depositStmt.setString(2, receiverID);
            depositStmt.executeUpdate();

            // Log the transaction
            String logSQL = "INSERT INTO Transactions (accountID, transactionType, amount, transactionDate) VALUES (?, ?, ?, ?)";
            try (PreparedStatement logStmt = conn.prepareStatement(logSQL)) {
                // Log for sender
                logStmt.setString(1, senderID);
                logStmt.setString(2, "Transfer");
                logStmt.setDouble(3, transferAmount);
                logStmt.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
                logStmt.executeUpdate();

                // Log for receiver
                logStmt.setString(1, receiverID);
                logStmt.setString(2, "Received");
                logStmt.setDouble(3, transferAmount);
                logStmt.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
                logStmt.executeUpdate();
            }

            conn.commit(); // Commit transaction
            JOptionPane.showMessageDialog(this, "Amount has been transferred successfully!");
        } catch (ClassNotFoundException | SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback(); // Rollback transaction on error
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            e.printStackTrace();
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (withdrawStmt != null) {
                    withdrawStmt.close();
                }
                if (depositStmt != null) {
                    depositStmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_TransferActionPerformed

    private void accNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        String URL = "jdbc:mysql://localhost:3306/BankSystem";
        String username = "root";
        String Password = "Radhika1@";
        String query = ("Select * from accounts where AccountID = ?;");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            java.sql.Connection connect = DriverManager.getConnection(URL, username, Password);
            PreparedStatement statement = connect.prepareStatement(query);
            statement.setString(1, (UserLogin.global.getID()));
            ResultSet data = statement.executeQuery();
            if (data.next()) {

                dispose();
                MainPage user;
                user = new MainPage();
                String userId = data.getString("balance");
                user.balance.setText(userId);
                String Name = data.getString("FirstName") + " " + data.getString("LastName");
                user.Name.setText(Name);
                user.pack();
                user.setLocationRelativeTo(null);
                user.show();

            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    public javax.swing.JLabel ID;
    private javax.swing.JButton Transfer;
    public javax.swing.JLabel User;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField accNo;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
